<?php

namespace BookingBundle\Entity;

use AppBundle\Entity\Repository;
/**
 * RoomCategorySeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomCategorySeasonRepository extends  Repository {
    
}
