<?php

namespace BookingBundle\Entity;

/**
 * RoomSeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomSeasonRepository extends \Doctrine\ORM\EntityRepository
{
}
