<?php

namespace BookingBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends Repository {
    
}
