<?php

namespace BookingBundle\Entity;

/**
 * SchedulerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerRepository extends \Doctrine\ORM\EntityRepository
{
}
